FROM php:7.4.13-apache

# NodeJS
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

# package install
RUN apt-get update && apt-get install -y zip unzip software-properties-common git nodejs sudo vim

# PHP extensions
RUN docker-php-ext-install pdo_mysql
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
  install-php-extensions zip gd

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer && rm -rf /var/lib/apt/lists/*

# LORIS
COPY . /var/www/loris/
RUN cd /var/www/loris && make
# cd /var/www/loris/tools && ./install.sh
